insert into locker_milestones (title, summary) values (
'Email pipeline now LIVE end-to-end on the new domain (miseai0010.com) — real email, real Gemini read, correctly audited',
'THE OLD DOMAIN (miseai-0000.com, hyphenated, registered through a registrar Mikey considers shady) is fully retired — deleted from Resend for good. NEW DOMAIN miseai0010.com (no hyphen, WordPress.com DNS) is now the live domain, verified in Resend for both sending AND receiving (DKIM/SPF/MX individually confirmed verified, not just inferred from overall domain status).

WHAT WAS CONFIRMED THIS SESSION, IN ORDER:
1. Root domain miseai0010.com verified in Resend (an anti-hijacking recent_owner_activity hold cleared on its own, faster than the ~8-day estimate — a subdomain workaround (mail.miseai0010.com) was started to route around the wait but abandoned once the hold cleared; that subdomain is NOT in use, one leftover unused DNS record and possibly a duplicate domain object in Resend from a since-cut-off session, harmless, cleanup only).
2. The inbound webhook pointing at email-inbound''s URL (https://qhfmywontdwwfapowqpo.supabase.co/functions/v1/email-inbound) was already live from before this session — confirmed by matching it to the historical Sept 7 proof event by job_id. Resend webhooks are account-wide, not domain-scoped, so no re-pointing was needed for the new domain.
3. client_email_routes already had invoices@miseai0010.com active, routing to the real client (Cellar, client_id 7d1f0a2e-6c44-4b9a-9f31-2ab8e5c07d10) — this was assumed not-yet-done earlier in the session and turned out to already be handled.
4. A REAL test email (not a Resend dashboard test button, not a manual curl/POST) was sent by Mikey to invoices@miseai0010.com with a real invoice photo (IMG_0565 (2).JPG) attached. Full four-point trace confirmed directly in Supabase: webhook received -> ingestion_queue row created -> process-queue picked it up ~1 min later (took 27.8s, real Gemini call) -> finished row landed in invoices (id 17b52ec5-2591-4786-981d-34dbcce50424), status completed.

EXTRACTION QUALITY ON THAT REAL INVOICE (Sysco - San Francisco #450043286, gemini-3.7-flash, first model in the fallback list, no fallback needed): 9 line items, subtotal and grand_total both $406.98, Postgres re-summed the lines and matched to the penny, zero money_problem/unit_problem flags. Correctly kept PACK ("6", "40", "ONLY") separate from SIZE (".5GAL", "8 OZ", "17 OZ") instead of merging them. The "ONLY" pack value (a real, deliberately odd Sysco convention) came through verbatim. The fuel surcharge line (no unit price, just an amount) came through correctly per prompt rule 7 (raw_quantity/raw_uom/raw_unit_price null, line_total populated) — only this one no-unit-price case has been proven on a real invoice so far; delivery fees, split-case fees, and keg deposits are the same code path but unconfirmed by direct example.

CODE-LEVEL CORRECTIONS FOUND WHILE VERIFYING (previously assumed differently in an external markdown handoff doc a prior session was also keeping — see note below):
- email-inbound does NOT verify a Resend webhook signing secret (whsec_...) despite Resend offering to generate one. It only checks an INBOUND_TOKEN secret via ?token=... query param or x-inbound-token header. GET the function URL (no auth needed) and read token_required in the JSON response to check if one is set.
- ingest-nightly-report only reads files[0] — if a restaurant emails multiple attachments to the sales@ / nightly_report address, every attachment after the first is silently dropped, no error. Worth fixing before this path is relied on for real.
- Job type (invoice vs nightly_report) is decided ONLY by which address an email was sent TO (client_email_routes.route_kind), never by inspecting attachment contents. Mixing an invoice photo and a nightly sales report in ONE email produces wrong results either way: sent to invoices@, the sales report gets fed through the invoice-specific Gemini schema (garbage read, likely flagged for review); sent to sales@, only the first attachment survives (see above). Always send invoice photos and nightly reports as separate emails to their respective addresses.

NOTE ON DOCUMENTATION: this session was also maintaining a separate markdown handoff file (MiseAI-Status-Handoff.md, uploaded/downloaded outside the database) in parallel with this locker system, without realizing the locker existed until partway through the session. Both now describe the same current state (email pipeline live), but future sessions should be aware TWO handoff mechanisms exist for this project and were not originally kept in sync — the locker (this table, in-database, was already the older/more established convention going back to Sept 6) and a markdown file (newer, external, used by a session that had not yet discovered the locker). Worth reconciling into one source of truth going forward, or at minimum cross-referencing both at the start of a session.'
);
