insert into locker_milestones (title, summary) values (
'Documentation consolidated: the locker is now the single source of truth (markdown handoff file retired)',
'A parallel markdown handoff file (MiseAI-Status-Handoff.md) had been kept outside the database this session, in parallel with this locker, without the session realizing the locker already existed until partway through. Decision made with Mikey: the locker is the single source of truth going forward. The markdown file is retired as of this entry — do not maintain it further; everything worth keeping from it has been folded into locker_milestones/locker_issues above.

ONE CORRECTION caught while reconciling the two: the markdown file claimed "27 tables still RLS-enabled-no-policy" as an open item. Checking locker_findings directly shows this is stale/imprecise — RLS was actually enabled on all 21 tables already (see finding 5c4772a4, resolved), 16 tables fully locked to anon/authenticated, and only the 5 tables the Review Queue page needs (invoices, invoice_line_items, ingredients, pnl_categories, invoice_corrections) still allow scoped anon access with no per-client filtering (see finding 9ac158b0, still open, has a password gate now but not per-client). The locker''s findings are the accurate version — the markdown file''s simplified "27 tables" framing should not be repeated.

KEY ROTATION PLAN (from the markdown file, not previously in the locker): Mikey wants ONE deliberate key rotation right before launch, covering Resend, Supabase, Gemini, everything at once — not piecemeal now while things are still unstable. Supabase''s newer key system (sb_publishable_/sb_secret_ replacing legacy anon/service_role JWTs) is deliberately NOT being migrated to yet; legacy keys keep working until end of 2026, so there is no rush forcing this before the planned rotation.

RESEND_API_KEY STATUS (unconfirmed, carried over from the markdown file): Mikey rotated the Resend API key (deleted old, created new) at some point before this session. Whether the new key was actually put into the Supabase Edge Function secret was never explicitly re-confirmed this session — though the real end-to-end test email did work, which is at least indirect evidence it is set correctly, since email-inbound needs RESEND_API_KEY to fetch attachment bytes from Resend''s API.'
);
